name: Slack Code Scanning Alerts

on:
  push:
    branches:
      - main
    paths:
      - '**.github/workflows/slack-alerts-template.yml'

jobs:
  send_alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
        with:
          status: ${{ job.status }}
          channel: 'github-advancedsecurity-test'
          text: 'Code scanning alert'
          fields: |
            [
              {
                "title": "Repository",
                "value": "${{ github.repository }}",
                "short": true
              },
              {
                "title": "Alert Level",
                "value": "${{ github.event.alert.rule.severity }}",
                "short": true
              },
              {
                "title": "Alert Message",
                "value": "${{ github.event.alert.message }}",
                "short": false
              }
            ]
          color: '#FF0000'
          username: 'GitHub Code Scanning'
